### ISSUE TITLE
Remove name and bio from user table

### ISSUE THREAD

**Issue by ChaelCodes** [ChaelCodes/MeetAnotherDay#182]
We're tracking name and bio on the profile table. We're doing this to support multiple profiles in the future on one user. (This feature may not manifest for a LONG time.) Therefore, we don't need a name and bio on the user table.

Please build a migration to drop them, run the migration, and commit the changes to db/schema.

**Comment by fransan6** [comment]
Afternoon - could I be assigned to this, please?

**Comment by ChaelCodes** [comment]
Sure! Thank you for picking this up!

**Comment by fransan6** [comment]
Sorry, but in point 3 of the [local setup guide](https://github.com/ChaelCodes/HallwayTracks/blob/main/CONTRIBUTING.md#dev-environment-setup-local), where do I obtain a username and password? Though I do see a username already if we're looking from lines 85-89 in `database.yml`:

```ruby
production:
  <<: *default
  database: ConfBuddies_production
  username: ConfBuddies
  password: <%= ENV['CONFBUDDIES_DATABASE_PASSWORD'] %> 
```

**Comment by ChaelCodes** [comment]
This should be your postgres username and password. Sometimes it's postgres/postgres and sometimes it's your computer's username.

You'll want to update the development section of the database config. The one you linked is only used in production.
