### ISSUE TITLE
Make a PR Template

### ISSUE THREAD

**Issue by ChaelCodes** [ChaelCodes/MeetAnotherDay#80]
# Description
We need a PR template in github.

It should have:
- `closes #` to encourage folks to add the issue
- a checklist: Did you add specs? Is the build green? etc
- Description header for the changes, and why we want them.

**Comment by LittleBigProgramming** [comment]
I've never made a PR template before and would like to figure out how to make one! 👀 

Would like to pick this up if possible 🙌

**Comment by LittleBigProgramming** [comment]
Thanks! This is super helpful!
